# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.
{
    'name': "gc_warranty",
    'version': '0.0.1',
    'category' : 'Product',
    'summary': """Módulo para gestion de garantias
                """,
    'author': 'Anderson Rodríguez',
    'company': 'Chakao',
    'maintainer': 'Anderson Rodríguez',
    'website': '',
    'description': "Gestion de garantías",
    'images' : [],
    'depends' : [
        'base',
        'account',
        'product',
        'stock',
        'approvals',
        'gchakao_custom',
        'sale',
    ],
    'data': [
        'security/res_groups.xml',
        'security/ir.model.access.csv',
        'data/warranty_request_data.xml',
        'data/mail_data.xml',
        'data/rule.xml',
        'wizards/manual_wizard.xml',
        'wizards/apply_credit_note_wizard.xml',
        'views/warranty_request_views.xml',
        'views/warranty_menu.xml',
        'views/approval_category_views.xml',
        'views/approval_request_views.xml',
        'views/product_views.xml',
        'views/stock_production_lot_view.xml',
        'views/res_config_settings_views.xml',
        'views/account_move_view.xml',
        'views/sale_order_view.xml',
    ],
    'demo': [],
    'qweb': [],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
