{
    'name': "gchakao_custom",
    'version': '0.1',
    'category' : 'ALL',
    'summary': """Desarrollos complementarios""",
    'author': 'Grupo Chakao',
    'company': 'Grupo Chakao',
    'maintainer': 'Grupo Chakao',
    'website': 'neumaticoschakao@gmail.com',
    'description': "Este addon contiene todas las personalizaciones de Grupo Chakao",
    'images' : [],
    'depends' : [
        'base',
        'web',
        'account',
        'hr_payroll',
        'hr_holidays',
        'l10n_ve_full',
        'l10n_ve_payroll',
        'account_dual_currency',
        'sale',
        'sale_management',
        'approvals',
        'purchase_requisition',
        'maintenance',
        'event',
        'fleet',
        'stock_dropshipping',
        'repair',
        'stock_landed_costs',
    ],
    'data': [
        "security/security.xml",
        'security/ir.model.access.csv',
        'data/approval.xml',
        'data/salary_rule.xml',
        'data/rule.xml',
        'data/mail_data.xml',
        'data/cron.xml',
        'data/ir_actions_server_data.xml',
        'views/hide_menu_view.xml',
        'views/res_config_settings_views.xml',
        # 'views/mail_activity_views.xml',
        # CONTABILIDAD
        'report/report_menu.xml',
        'report/report_invoce_letter.xml', # TAMAÑO CARTA
        'report/report_invoce_half_letter.xml', # TAMAÑO MEDIA CARTA
        'report/report_purchase_me_without_iva.xml',
        'report/report_purchase_me_with_iva.xml',
        'views/account_move_view.xml',
        'views/account_journal_view.xml',
        'views/account_payment_view.xml',
        'report/purchase_me_invoice_report.xml',
        # 'views/account_payment_method_view.xml',
        'views/gc_account_payment_method_view.xml',
        'views/intercompany_transfer_view.xml',
        'views/transaction_classification_views.xml',
        'wizard/wizard_analysis_ledger.xml',
        'report/analysis_ledger_report.xml',
        'wizard/vat_summary.xml',
        'report/report_vat_summary.xml',
        'wizard/bank_conciliation.xml',
        'report/report_bank_conciliation.xml',
        # 'views/invoice_paid.xml',
        'wizard/account_move_reversal.xml',
        'wizard/gc_account_payment_wizard.xml',
        'wizard/account_receivable.xml',
        'report/report_account_receivable.xml',
        'wizard/account_receivable_supplier.xml',
        'report/report_account_receivable_supplier.xml',
        'wizard/account_receivable_subprovider.xml',
        'report/report_account_receivable_subprovider.xml',
        'wizard/account_status.xml',
        'report/report_account_status.xml',
        'report/report_account_status_detailed.xml',
        'wizard/account_status_supplier.xml',
        'report/report_account_status_supplier.xml',
        'report/report_account_status_detailed_supplier.xml',
        'wizard/account_status_subprovider.xml',
        'report/report_account_status_subprovider.xml',
        'report/report_account_status_detailed_subprovider.xml',
        'views/account_payment_term_views.xml',
        'views/account_move_line_view.xml',
        'report/report_receipt_payment.xml',
        'report/gc_account_payment_template.xml',
        'report/account_wh_islr_report_comprobante_inherit.xml',
        'report/account_wh_iva_report_comprobante_inherit.xml',
        'report/gc_account_payment_igtf_template.xml',
        'wizard/void_invoice.xml',
        'wizard/account_debit_note_view.xml',
        'wizard/gc_account_payment_igtf_wizard.xml',
        # VENTAS
        'wizard/sale_order_product_select.xml',
        'views/sale_order_view.xml',
        "wizard/product_price_list.xml",
        "wizard/price_list_multicompany.xml",
        "report/product_price_list_report.xml",
        "report/price_list_multicompany_report.xml",
        'views/res_users_view.xml',
        "views/product_template.xml",
        "views/product_view.xml",
        'wizard/assign_tracking_number_wizard.xml',
        "views/stock_picking_views.xml",
        "views/stock_move_views.xml", 
        "views/stock_move_line_views.xml",
        "report/report_picking_extra.xml",
        "report/delivery_order_report.xml",
        "report/report_consumable_output_order.xml",
        "report/report_purchase_order_me.xml",
        "report/report_purchase_order_pm.xml",
        "report/physical_stocktaking_report.xml",
        "wizard/physical_stocktaking.xml",       
        "views/fleet_vehicle_views.xml",
        "views/approval_request_views.xml",
        "views/approval_category_views.xml",
        "views/purchase_order_views.xml",
        "views/purchase_requisition_views.xml",
        'views/res_partner_view.xml',
        'views/res_bank_views.xml',
        'views/customer_group_view.xml',
        'report/report_sale_order_budget.xml',
        'wizard/sale_order_discount_views.xml',
        # RRHH
        'data/reglas_vacaciones.xml',
        'wizard/empleados_wizard.xml',
        'wizard/hr_payroll_payslips_by_employees_views.xml',
        'wizard/commission_update_wizard.xml',
        'wizard/pre_payroll_wizard.xml',
        'report/report_pre_payroll_detailed.xml',
        'report/report_pre_payroll_analytic.xml',
        'report/report_pre_payroll_summarized.xml',
        'wizard/resume_payroll_wizard.xml',
        'report/report_resume_payroll.xml',
        "views/hr_payroll_structure_views.xml",
        "views/hr_payslip_views.xml",
        "views/hr_payslip_run_views.xml",
        'report/report_payslip_templates.xml',
        'report/report_payslip_ba_templates.xml',
        'report/report_payslip_ct_templates.xml',
        'report/report_payslip_vacation.xml',
        "views/hr_contract_views.xml",
        "views/hr_rate.xml",
        "views/hr_payroll_structure_type_views.xml",
        "views/hr_discount_type.xml",
        "views/hr_payslip_discount_resume.xml",
        "views/hr_payslip_discount_details.xml",
        "views/hr_payment_order.xml",
        'wizard/wizard_forma_13_12.xml',
        # MANTENIMIENTO
        'views/maintenance_request.xml',
        # BATERIAS
        'wizard/stock_assign_serial_numbers.xml',
        'views/stock_quant_views.xml',
        'views/stock_lot_views.xml',
        # Landed costs
        'views/landed_cost_view.xml',
        "wizard/merch_transit_wizard.xml",
        # COMPANY
        'views/res_company.xml',
        # DISPATCH CONTROL
        'data/dispatch_control_data.xml',
        "report/dispatch_control_report.xml",
        'views/stock_move_line_views.xml',
        'views/dispatch_control_view.xml',
        # FUERZA DE VENTAS
        'views/sales_force_views.xml',   
    ],
    # 'assets': {
    #     'web.assets_backend': [
    #         'gchakao_custom/static/xml/conf.xml',
    #         'gchakao_custom/static/js/switchcompany.js',
    #     ],
    # },
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}