# -*- coding: utf-8 -*-

from . import sale_order_product_select
from . import hr_payroll_payslips_by_employees
from . import product_price_list
from . import price_list_multicompany
from . import physical_stocktaking
from . import commission_update_wizard
from . import account_receivable
from . import account_receivable_supplier
from . import account_receivable_subprovider
from . import account_status
from . import account_status_supplier
from . import account_status_subprovider
from . import bank_conciliation
from . import vat_summary
from . import stock_assign_serial_numbers
from . import assign_tracking_number_wizard
from . import pre_payroll_wizard
from . import account_move_reserval
from . import gc_account_payment_wizard
from . import resume_payroll_wizard
from . import merch_transit_wizard
from . import wizard_analysis_ledger
from . import wizard_forma_13_12
from . import empleados_wizard
from . import void_invoice
from . import account_debit_note
from . import sale_order_discount
from . import account_fiscal_book_wizard
from . import gc_account_payment_igtf_wizard